image: continuumio/miniconda3:latest

test:
  script:
    - apt-get update -q -y
    - apt-get install -y build-essential
    - conda env create -f cicd/environment_cpu.yaml
    - source activate crest_cpu
    - pytest

