[build-system]
requires = ["setuptools>=61.0", "wheel", "setuptools_scm[toml]>=3.4.3"]
build-backend = "setuptools.build_meta"

[project]
name = "crest"
version = "0.0.1"
description = "AI-based python framework for coupling tensor network models."
readme = "README.rst"
requires-python = ">=3.7"

[tool.setuptools.packages.find]
include = ["crest*"]
exclude = ["examples*", "docs*", "tests*"]
