[pytest]
cache_dir = .cache/pytest

filterwarnings =
    ignore::DeprecationWarning
    ignore::dill.PicklingWarning

testpaths =
    tests
    
markers =
    integtest: Mark a test as an integration test (not unit).
    examples: Mark a test as an example notebook test (requires --examples to run).