from collections.abc import Collection, Sequence
from functools import cached_property, partial
from typing import Union
from typing import Callable

import dask.dataframe as dd
import dask.array as da 
import numpy as np 
import logging
import numbers
import time 
import dask 

from crest.base import BaseSet
from crest.utils import find_neighbors, Stopwatch
from .SampleSet import SampleSet
from .Block import Block


# Some type checkers report Literal numbers aren't compatible with Number
Number = numbers.Real | int | float


class Blockset(BaseSet):
    """Wraps a collection of Blocks into a single object.

    Parameters
    ----------
    blocks : Collection[Block]
        The set of Blocks which form this Blockset. Because this inherits from 
        BaseSet, functions existing in the Block class can be called by this 
        Blockset object in order to apply the function across all Blocks in 
        this set. See crest.base.BaseSet for more details.
    logger : logging.Logger | None
        Logger object to use when logging.
    timing : bool
        Whether timing benchmarks should be included when logging.
    shuffle : bool
        Whether the samples generated by find_matches should be shuffled.

    """
    def __init__(self,
        blocks  : Union[Collection[Block] | Collection[Callable]],
        logger  : Union[logging.Logger, None] = None,
        timing  : bool = True,
        shuffle : bool = False,
    ):
        self.container = [getattr(b, '__call__', lambda: b)() for b in blocks]
        self.logger  = logger or logging.getLogger('Blockset')
        self.timing  = timing and (logger is not None)
        self.shuffle = shuffle
        self.dropped = [] 
        self.dropped_features = []
        self.dtype = np.dtype([(f'Data_{i}', b.dtype) for i,b in enumerate(self)])

        # Set block count for all blocks
        for i, block in enumerate(self.container):
            setattr(block, 'block_count', len(self.container))
            setattr(block, 'block_index', i)
            if self.timing: 
                setattr(block, 'logger', self.logger)


    def __repr__(self) -> str:
        return f'Blockset[{"".join(str(b.block_index) for b in self)}]'


    @cached_property
    def benchmark(self):
        """ Return a Stopwatch function for benchmarking """
        return lambda label, logger=self.logger.debug, **kwargs: Stopwatch(**({
            'message' : f'\t\t{self}.{label}',
            'logger'  : logger, # Don't log when time < 0.05 seconds
            # 'silent'  : {'time': 0.05} if self.timing else True, 
        } | kwargs))


    def find_matches(self, 
        task_bytes     : Number = 1e9, 
        task_samples   : int  | None = None,
        features       : list | None = None,
        valid_percents : dict | None = None,
        drop_datafiles : list | None = None,
        verbose        : bool = False,
    ) -> da.Array:
        """Find all valid samples when matching up Blocks in this Blockset.
        
        Parameters
        ----------
        task_bytes : Number
            Note this parameter is superceded by the task_samples parameter, 
            and so task_bytes will be ignored if task_samples is set. Controls
            the size, in bytes, of each task (block) contained in the returned 
            dask array. In other words, the returned array will have a number
            of lazily computed pieces, each generating a portion of the full
            amount of valid samples; task_bytes controls the number of samples
            contained in each of these pieces, based on the number of bytes 
            needed to represent those samples. 
        task_samples : int | None
            The number of samples that should be contained in each task (block)
            of the returned dask array. In other words, the returned array will
            have a number of lazily computed pieces, each generating a portion 
            of the full amount of valid samples; task_samples controls the 
            number of samples contained in each of these pieces.
        features : list[str] | None
            A list of the features that should be used when creating samples.
            If features are known ahead of time and are given, then the output
            representation is rigid and therefore the process can be much 
            faster. Otherwise, Sample objects are created for each element,
            containing all information and providing a flexible representation.
        valid_percents : dict[str, dict[str, float]] | None
            One item of the Batcher.valid_percents list, representing a mapping
            of {Block name: {coordinate: valid percent}}. See the docstring of
            Batcher for further discussion.
        drop_datafiles : list[str] | None 
            One item of the Batcher.drop_datafiles list, representing a list of
            the names of Blocks which should be excluded when calculating the
            valid samples of this Blockset. See the docstring of Batcher for
            further discussion.
        verbose : bool
            Adjust the logger verbosity level to DEBUG, and log all timing 
            benchmarks (even if Blockset was initialized with timing=False).

        Returns
        -------
        dask.Array
            Returns a lazy dask array containing the valid sample matchups (the 
            combination of samples from each Block which are near enough to be
            considered neighbors).

        """
        if verbose:
            self.logger.setLevel(logging.DEBUG)
            self.timing = True

        # Create meta/dtype information for dask
        meta = np.empty(0, dtype=self.dtype)

        # Create a new Blockset object which excludes the specified Blocks
        if drop_datafiles is not None:
            self = self._exclude(drop_datafiles, features)

        # Set new valid percent configurations
        if valid_percents is not None:
            for key, vp in valid_percents.items():
                for i, block in enumerate(self):
                    if (key==i if isinstance(key,int) else key in block.label):
                        block.set_valid_percents(vp)

        # Benchmark timing for data loading / neighbor finding
        with self.benchmark('find_matches') as timer:
            timer.message += ' | 100% of time spent loading data'

            # Sort by sparsity, assuming higher values are more likely to fail
            by_sparsity = sorted(self, key=lambda b:b.sparsity, reverse=True)

            # Fast return when there are no valid windows for a block
            with self.benchmark('fast_invalid_check'):
                for block in by_sparsity:
                    if block.fast_invalid_check:
                        self.logger.debug(f'\t{block} failed fast_invalid_check')
                        return da.from_array(meta)

            # Return when there are no valid windows for a block
            with self.benchmark('valid_windows.size'):
                for block in by_sparsity:
                    if not block.valid_windows.size:
                        self.logger.debug(f'\t{block} failed valid_windows.size')
                        return da.from_array(meta)

            loading_time = time.time() - timer.start['time']

            # Find neighboring points between coordinate grids for the valid window
            # locations, within the resolution tolerances provided
            with self.benchmark('find_neighbors'):
                matches, counts = find_neighbors(
                    self.valid_coords, 
                    self.valid_resolution,
                    grid_labels = [str(b) for b in self],
                    axis_labels = [b.dims for b in self],
                    num_samples = task_samples or -1,
                    logger  = self.logger if self.timing else None,
                    shuffle = self.shuffle,
                    debug   = False,
                )

            complete_time = time.time() - timer.start['time']
            loading_pct   = (loading_time / complete_time) * 100
            timer.message = timer.message.replace('100', f'{loading_pct:.0f}')

        # Undo the valid_percents modification(s)
        if valid_percents is not None:
            self.reset_valid_percents()

        # for block in self:
        #     block.__dict__.pop('valid', None)

        # Return if there aren't any matches
        if matches.size < 1: return da.from_array(meta)

        task_mb = f'Task={task_bytes/1e6:.0f} MB'
        with self.benchmark(f'_grouped (shape={matches.shape} | {task_mb})'):
            matches, divs, lengths = self._grouped(matches, counts, task_bytes, task_samples)

        # Create a dask dataframe first, then transform into a dask
        # array (in order to satisfy dask's built in assumptions)
        kwargs = {
            # 'meta'             : (0, int), 
            #'token'            : f'product{id(matches)}',
            # 'divisions'        : [0] + divs.tolist(), 
            # 'enforce_metadata' : False,
            'features'         : self.feature_subset(features),
            'make_objs'        : features is None,
            'singleton'        : len(lengths) == 1,
        }

        # try:
        #     return dd.from_map(self._parse, matches, lengths, **kwargs
        #         ).to_dask_array(lengths=list(lengths), meta=meta)
        # # Newer dask version does not have token keyword
        # except:
        #     kwargs.pop('token')
        #     return dd.from_map(self._parse, matches, lengths, **kwargs
        #         ).to_dask_array(lengths=list(lengths), meta=meta)

        # After dask==2023.3.0, there is a change to dataframe which causes
        # the prior approach (building an array from a dataframe) to run >2x 
        # slower: https://github.com/dask/dask/commit/89db50e5d874cf999987344c44168d7b725810c5#diff-7f08628a92dd3add9053c4e6ede5459803a8e3e1f78464f356c65a75a6872a99L374
        # 
        # To avoid this issue, we can instead build the array by concatenating
        # a list of delayed objects together. This approach is as fast as the
        # dataframe method, and is not impacted by the change in v2023.3.1
        delay = dask.delayed(partial(self._parse, **kwargs))
        tasks = [task.values for task in map(delay, matches, lengths)]
        array = partial(da.from_delayed, meta=meta)
        return da.concatenate(map(array, tasks, lengths[:, None]))


    def _parse(self, 
        matches   : Union[Sequence, np.ndarray],
        n_samples,# : int,
        features,#  : list[list[str]],
        make_objs : bool,
        singleton : bool,
    ) -> SampleSet:
        """ Parse a match into the relevant SampleSet of data.
        
        Notes
        -----
        If features are known ahead of time and are given, then the output
        representation is rigid and therefore the process can be much 
        faster. Otherwise, Sample objects are created for each element,
        containing all information and providing a flexible representation.           

        """
        with self.benchmark(f'_parse.extract (shape={matches[0].shape})'):
            windows = self.extract(_map=[matches, features]) # Extract data windows
            # ordered = self.sort(container=windows) # Return to original ordering

        # Re-add dropped Block features as NaN
        for block, block_features in zip(self.dropped, self.dropped_features):
            block_window = block.extract(np.zeros(1), block_features, empty=True)
            sample_count = len(matches[0])

            if make_objs: 
                block_window = [block_window] * sample_count
            else:         
                block_window, dtype = block_window
                block_window = (np.array([block_window] * sample_count), dtype)
            windows.container.insert(block.block_index, block_window)

        # Zip the matches from each Block together to form the final Samples
        if make_objs: windows, dtypes = list(zip(*windows)), self.dtype
        else:         windows, dtypes = list(zip(*windows))
        return SampleSet(windows, int(n_samples), make_objs, singleton, dtypes)
        

    def _grouped(self, 
        matches      : np.ndarray, 
        counts       : Union[np.ndarray, None], 
        task_bytes   : Number,
        task_samples : Union[int, None],
    ):
        """ Combine matches into larger groups for higher throughput """
        # Number of samples in the cartesian product for dataframe divisions
        if counts is None:
            int_dtype = np.int32 
            cartesian = np.ones(matches.shape[1], int_dtype)
        else:
            int_dtype = counts.dtype
            cartesian = np.prod(counts, axis=0).astype(int_dtype)
        divisions = np.cumsum(cartesian, dtype=int_dtype)

        # Combine multiple match sets together into a single SampleSet for 
        #   faster processing, with up to `task_bytes` of data per SampleSet
        # This also drastically reduces memory and time used by dd.from_map
        maxim = task_samples or (task_bytes / self.dtype.itemsize)
        total = divisions[-1]
        first = divisions[0]
        n_ele = int(min(maxim, total))

        # Check that groups actually need combining to reach size threshold
        if n_ele > cartesian.min():

            # Determine unique indices of the boundaries where matches should split
            boundaries = np.arange(max(first+1, n_ele), total, n_ele)
            partitions = np.searchsorted(divisions, boundaries)
            unique_idx = np.flatnonzero(np.diff(partitions, prepend=-1))

            # Create combined match sets and recompute dataframe divisions
            matches   = np.split(matches, partitions[unique_idx], axis=1)
            hist_bins = np.r_[0, boundaries[unique_idx], total]
            cartesian = np.histogram(divisions, hist_bins, weights=cartesian)[0]
            cartesian = cartesian.astype(int_dtype)
            divisions = np.cumsum(cartesian.copy(), dtype=int_dtype)

        # Otherwise just reshape to mimic having 1 set of matches per SampleSet
        else: matches = matches.T[..., None]
        return matches, divisions, cartesian


    def _exclude(self, names: list[str | int], features) -> 'Blockset':
        """ Create a new Blockset object that excludes the specified Blocks """
        blocks = Blockset([], self.logger, self.timing, self.shuffle)
        select = lambda i, b, n: (n==i) if isinstance(n,int) else (n in b.label)
        remove = lambda i,block: any(map(lambda n: select(i, block, n), names))

        # Remember both the kept and dropped blocks, plus any dropped features
        keep = [block for i, block in enumerate(self) if not remove(i, block)]
        drop = [block for i, block in enumerate(self) if     remove(i, block)]
        setattr(blocks, 'container', keep)
        setattr(blocks, 'dropped',   drop)
        setattr(blocks, 'dropped_features', [b.feature_subset(features) for b in drop])
        setattr(blocks, 'dtype', self.dtype)
        assert(len(blocks)), f'All Blocks excluded from {self} using {names}'
        return blocks
