from __future__ import annotations
from queue import Empty
from tlz import merge_with
import numpy as np 

from .BlockConfig import BlockConfig


class BatchCombiner:
    """Combine batches generated by different configurations into one batch.

    Parameters
    ----------
    configs : list[BlockConfig]
        The list of Block configurations that will be generating batches. 
    features : list | None
        Feature structure of each batch, or None if batches are composed of
        Sample objects. See the Batcher docstring for further discussion.
    shuffle : bool
        Whether batches should be combined in a random order. 
    seed : int
        Random seed for shuffling. 
        
    """
    def __init__(self,
        configs    : list[BlockConfig], 
        features   : list | None,
        shuffle    : bool = True,
        seed       : int | None = None,
    ):
        self.configs = {hash(c): c for c in configs}
        self.batches = {c: [] for c in self.configs}
        self.features = features
        self.shuffle = shuffle
        self.random = np.random.default_rng(seed)
        
    
    def __str__(self) -> str:
        return 'BatchCombiner:\n\t' + '\n\t'.join([
            f'{self.configs[c]} has {len(v)} batches ready'
            for c,v in self.batches.items()])
        

    def __call__(self, 
        config_hash : int, 
        batches     : dict | list, 
        method      : str = 'append',
    ) -> 'BatchCombiner':
        """Store new batch(es) generated by a configuration.
        
        Parameters
        ----------
        config_hash : int
            The hash of the BlockConfig that generated this batch.
        batches : dict | list
            The batch (or list of batches) of samples to store.
        method : str
            Method to use when storing in the list of batches; can
            be either 'append' or 'extend', depending on whether a
            single batch is given or a list of batches.
            
        Returns
        -------
        BatchCombiner
            Returns a reference to itself.

        """
        getattr(self.batches[config_hash], method)(batches)
        return self 


    def __len__(self):
        """ Return the number of combined batches currently available """
        return min(map(len, self.batches.values()))


    def __iter__(self):
        """ Iterate through all combined batches that are available """
        for _ in range(len(self)):
            yield self.next()


    def __next__(self):
        """ Return one combined batch, if any are available """
        if len(self):
            return self.next()
        raise StopIteration


    def _get_batch(self):
        """ Create a batch by combining one batch from each BlockConfig """
        # Raise queue.Empty for compatibility with Batcher._get_queue_batch
        if not len(self): raise Empty
        
        batch = []
        for config_hash, config in self.configs.items():
            items = self.batches[config_hash]

            # Pull a random batch from those available
            if self.shuffle:
                index = self.random.integers(len(items))

                # Perform a swap/pop() to avoid O(n) complexity of pop(index) 
                items[index], items[-1] = items[-1], items[index]
                batch.append(items.pop())
            else: batch.append(items.pop(0))

            # Decrement the number of queued samples for this BlockConfig
            with config: 
                config.n_queued = max(0, config.n_queued-1)

        # Total batch size will now be `batch_size*len(self.configs)`
        return batch


    def next(self):
        """Combine individual batch dictionaries and arrays. 
        
        Notes
        -----
        All individual batches must have the same structure as the specified
        feature structure. This should be guaranteed as long as all workers
        are using the same Batcher.features attribute value. See the Batcher
        docstring for further discussion on the possible structure of features. 

        """

        # If no features are specified, return the list of individual batches
        if self.features is None: return self._get_batch()

        def combine(features, *batches):
            """ Combine batches using the same nesting format as features """
            if isinstance(features[0], str) or not hasattr(features[0], '__len__'):
                return merge_with(np.concatenate, *batches)
            return type(features)(map(combine, features, *batches))
        return combine(self.features, *self._get_batch())


    def update_queued(self):
        """Update config inferred values with the true values.

        Notes
        -----
        If a worker process dies, the configuration counters affected by that
        worker will be permanently incorrect (which, in the worst case, could
        lead to the Batcher hanging because workers think batch queues are at
        capacity). This function can be called to ensure counters used by the
        workers are updated to reflect the true count of queued batches.
        
        """
        
        for config_hash, config in self.configs.items():
            with config:
                config.n_queued = len(self.batches[config_hash])
                config.n_worker = 0