from queue import Empty
from tlz import merge_with
import numpy as np 

from .BlockConfig import BlockConfig


class BatchCombiner:
    """Combine batches generated by different configurations into one batch.

    Parameters
    ----------
    configs : list[BlockConfig]
        The list of Block configurations that will be generating batches. 
    features : list | None
        Feature structure of each batch, or None if batches are composed of
        Sample objects. See the Batcher docstring for further discussion.
    batch_size : int
        Number of samples contained in each batch (i.e. Batcher.batch_size).

    """
    def __init__(self,
        configs    : list[BlockConfig], 
        features   : list | None,
        batch_size : int, 
    ):
        self.configs = {hash(c): c for c in configs}
        self.batches = {c: [] for c in self.configs}
        self.features = features
        self.batch_size = batch_size


    def __call__(self, batch, config_hash: int) -> 'BatchCombiner':
        """Store a new batch generated by a configuration.
        
        Parameters
        ----------
        batch
            The batch of samples to store.
        config_hash : int
            The hash of the BlockConfig that generated this batch.

        Returns
        -------
        BatchCombiner
            Returns a reference to itself.

        """
        self.batches[config_hash].append(batch)
        return self 


    def __len__(self):
        """ Return the number of combined batches currently available """
        return min(map(len, self.batches.values()))


    def __iter__(self):
        """ Iterate through all combined batches that are available """
        for _ in range(len(self)):
            yield self.next()


    def __next__(self):
        """ Return one combined batch, if any are available """
        if len(self):
            return self.next()
        raise StopIteration


    def _get_batch(self):
        """ Create a batch by combining one batch from each BlockConfig """
        # Raise queue.Empty for compatibility with Batcher._get_queue_batch
        if not len(self): raise Empty
        
        batch = []
        for config_hash, config in self.configs.items():
            batch.append(self.batches[config_hash].pop(0))

            # Decrement the number of queued samples for this BlockConfig
            with config: config.n_queued.value -= self.batch_size

        # Total batch size will now be `self.batch_size*len(self.configs)`
        return batch


    def next(self):
        """Combine individual batch dictionaries and arrays. 
        
        Notes
        -----
        All individual batches must have the same structure as the specified
        feature structure. This should be guaranteed as long as all workers
        are using the same Batcher.features attribute value. See the Batcher
        docstring for further discussion on the possible structure of features. 

        """

        # If no features are specified, return the list of individual batches
        if self.features is None: return self._get_batch()

        def combine(features, *batches):
            """ Combine batches using the same nesting format as features """
            if isinstance(features[0], str) or not hasattr(features[0], '__len__'):
                return merge_with(np.concatenate, *batches)
            return type(features)(map(combine, features, *batches))
        return combine(self.features, *self._get_batch())