from ctypes import c_int
import multiprocessing as mp
import numpy as np


class BlockConfig(dict):
    """Defines configuration parameters for computing samples from a Block.

    Notes
    -----
    This class contains numeric attributes shared by all worker processes. When
    a worker is ready to compute a new block, it looks at the list of 
    BlockConfig objects to determine which configuration to use when computing
    that block; i.e. it checks which configuration is most needed to create 
    batches (due to a lack of samples currently available from that config).
    
    To determine that, we can check three values that track the current status
    with respect to each configuration: 
        1. how many samples are queued and waiting to be used (n_queued) 
        2. how many workers are computing a block (n_worker) 
        3. how many samples can be expected from a block (avg_size)
    
    From these, we can calculate the currently expected number of samples for
    each configuration (n_queued + n_worker * avg_size) and pick the 
    BlockConfig that has the smallest value. In this way, a worker will use the 
    configuration that is most likely to generate samples that will allow more 
    batches to be created (via generation of the most needed samples).

    Parameters
    ----------
    **config
        Dictionary containing the configuration to use when computing samples
        from a block. Possible keys are {valid_pct, dropped}; see 
        crest.data.loading.Block.find_matches for further details. 

    """

    def __init__(self, numblocks, **config):
        super().__init__(**config)
        mp_context = mp.get_context('spawn')
        self._lock = mp_context.Lock()
        self._hash = hash(str(config))

        # Number of blocks this config has been used to compute
        self.n_blocks = mp_context.Value(c_int) 
        self.n_blocks.value = 0

        # Average number of samples generated by a block using this config
        self.avg_size = mp_context.Value(c_int) 
        self.avg_size.value = 1

        # Number of workers currently computing blocks with this config
        self.n_worker = mp_context.Value(c_int) 
        self.n_worker.value = 0

        # Number of samples generated by this config waiting in the queue
        self.n_queued = mp_context.Value(c_int) 
        self.n_queued.value = 0

        # Total number of blocks overall
        self.total_blocks = mp_context.Value(c_int)
        self.total_blocks.value = 0

        # Keep track of blocks that produced 0 samples for this config
        block_count = int(np.prod(np.atleast_1d(numblocks)))
        valid_array = np.ones(block_count, dtype=int)
        self._valid_blocks = mp_context.Array(c_int, list(valid_array))
        

    def __enter__(self):
        """ Allow atomic get/set operations via BlockConfig context manager """
        self._lock.__enter__()

    def __exit__(self, *args, **kwargs):
        """ Release resources upon exit of the context manager """
        self._lock.__exit__(*args, **kwargs)


    def __repr__(self) -> str:
        keys = ['n_blocks', 'avg_size', 'n_worker', 'n_queued']
        vals = {key: getattr(self, key).value for key in keys}
        vals['n_expected'] = vals['n_queued']+vals['n_worker']*vals['avg_size']
        string = ', '.join(f'{key}={val}' for key,val in vals.items())
        return f'BlockConfig({self._hash}: {string})'


    def __hash__(self) -> int:
        """ Allow BlockConfig to be used as a dictionary key """
        return self._hash


    def __lt__(self, other_config: 'BlockConfig') -> bool:
        """ Allow min and sorted to be used on a list of BlockConfigs """
        return self.n_expected < other_config.n_expected


    def set_n_blocks(self, total_blocks: int) -> None:
        """ Validate and set the actual number of blocks generated """
        if total_blocks > len(self._valid_blocks):
            raise Exception( 'Generated more blocks than expected: '+
                            f'{total_blocks=} vs {len(self._valid_blocks)=}' )
        with self:
            if self.total_blocks.value not in [0, total_blocks]:
                raise Exception( 'Processes have differing block counts: '+
                                f'{total_blocks=} vs {self.total_blocks.value=}' )
            if self.total_blocks.value == 0:
                self.total_blocks.value = total_blocks


    @property
    def valid_blocks(self):
        """ Return read-only array containing only the indices being used """
        return np.array(self._valid_blocks)[:self.total_blocks.value]


    @property
    def nonzero(self):
        """ Return all block indices where this config produces samples """
        indices = np.where(self.valid_blocks)[0]
        if len(indices) == 0:
            raise Exception(f'{self} cannot generate samples from any blocks')
        return indices


    @property
    def n_expected(self) -> int:
        """ Expected number of samples available from this config """
        n_queued = self.n_queued.value
        n_worker = self.n_worker.value
        avg_size = self.avg_size.value
        assert(n_queued >= 0), self
        assert(n_worker >= 0), self
        assert(avg_size >= 1), self
        return n_queued + n_worker * avg_size


    def add_worker(self) -> 'BlockConfig':
        """ Increment number of workers currently working on this config """
        with self: 
            self.n_worker.value += 1
        return self 


    def add_samples(self, block_idxs, n_samples: int) -> 'BlockConfig':
        """ Update counters when new samples are created from a block """
        with self:
            if n_samples == 0:
                for i in block_idxs:
                    self._valid_blocks[i] = 0
            self.avg_size.value = max(1, 
                (self.avg_size.value * self.n_blocks.value + n_samples) // 
                (self.n_blocks.value + 1)
            )
            self.n_queued.value += n_samples
            self.n_blocks.value += 1
            self.n_worker.value -= 1
        return self
