# CREST GPU environment
name: crest

channels:
 - conda-forge
 - defaults

dependencies:
  - python=3.9.15
  - tensorflow-gpu=2.7.0
  - pytest=7.2.0
  - networkx=2.8.8
  - matplotlib=3.6.2
  - ipykernel=6.19
  - cloudpickle=2.2.1
  - pyvis
  - pydot
  - graphviz
  - lambdajson
