# Hard requirements for running documentation generator (sphinx)
# WARNING: Keep this up-to-date!
name: OCETRA_cpu
channels:
 - conda-forge
 - nodefaults

dependencies:
  - apscheduler
  - awscli
  - boto3
  - bottleneck
  - cdsapi
  - cfgrib
  - cloudpickle
  - cmake
  - crick
  - cython
  - dask=2025.5.0
  - datapi
  - dill
  - earthaccess
  - ecmwf-api-client
  - fastapi
  - fsspec
  - gcc_linux-64
  - gxx_linux-64
  - geopandas
  - h5netcdf
  - hdf5
  - ipykernel
  - ipywidgets
  - libgdal-hdf4 
  - jsonpickle
  - make
  - matplotlib
  - msgraph-sdk
  - nbconvert
  - nbformat
  - netCDF4
  - networkx
  - numpy=2.2.6
  - opencv
  - osmnx
  - pandas
  - pip
  - polars
  - prettytable
  - pyarrow
  - pytest
  - python=3.12.11
  - python-daemon
  - pyvis
  - rasterio
  - s3fs
  - s3path
  - scikit-learn
  - seaborn
  - setuptools
  - sparse
  - tensorflow=2.18.0=cpu_py312h69ecde4_52
  - tiledb-py
  - tqdm
  - uvicorn
  - xarray
  - zarr=2.18.7
  
  # for docs
  - docutils
  - flit
  - furo
  - myst-nb
  - nbsphinx
  - nbsphinx-link
  - pandoc
  - sphinx
  - sphinx-autodoc-typehints
  - sphinx_rtd_theme
  - pydata-sphinx-theme
  - sphinxcontrib-mermaid


