# Hard requirements for running documentation generator (sphinx)
# WARNING: Keep this up-to-date!
name: OCETRA_cpu
channels:
 - conda-forge
 - nodefaults

dependencies:
  - apscheduler
  - awscli
  - boto3
  - bottleneck
  - cdsapi
  - cfgrib
  - cloudpickle
  - cmake
  - configparser
  - cython
  - dask=2025.5.0
  - datapi
  - dill
  - donfig
  - earthaccess
  - ecmwf-api-client
  - fastapi
  - fsspec
  - gcc_linux-aarch64
  - gxx_linux-aarch64
  - geopandas
  - h5netcdf
  - hdf5
  - ipykernel
  - ipywidgets
  - libgdal-hdf4 
  - jax=0.5.2
  - jsonpath-ng
  - jsonpickle
  - make
  - matplotlib
  - nbconvert
  - nbformat
  - netCDF4
  - networkx
  - numpy=2.2.6
  - opencv
  - osmnx
  - pandas
  - paramiko
  - pip
  - polars
  - prettytable
  - pyarrow
  - pygeogrids
  - pykdtree
  - pyresample
  - pytest
  - python=3.12.13
  - python-daemon
  - pyvis
  - rasterio
  - s3fs
  - s3path
  - scikit-learn
  - seaborn
  - setuptools
  - simple_slurm
  - sparse
  - sysrsync
  - tensorflow=2.18.0=cpu_py312h0267799_2
  - tiledb-py
  - tqdm
  - xarray=2025.12.0
  - yapf
  - zarr=2.18.7
  
  # for docs
  - docutils
  - flit
  - furo
  - myst-nb
  - nbsphinx
  - nbsphinx-link
  - pandoc
  - pydata-sphinx-theme
  - sphinx
  - sphinx-autodoc-typehints
  - sphinx_rtd_theme
  - sphinxcontrib-mermaid

  #for pytest
  - pip:
      - crick
  #for ingest
      - configobj
      - ismn
      - more_itertools
      - pygeobase
      - pynetcf
      - repurpose
      - tiledb


