# Hard requirements for running documentation generator (sphinx)
# WARNING: Keep this up-to-date!
name: OCETRA_cpu
channels:
 - conda-forge
 - nodefaults

dependencies:
  - apscheduler
  - awscli
  - boto3
  - bottleneck
  - cdsapi
  - cfgrib
  - cloudpickle
  - cmake
  - cython
  - dask=2025.5.0
  - datapi
  - dill
  - earthaccess
  - ecmwf-api-client
  - fastapi
  - fsspec
  - gcc_linux-aarch64
  - gxx_linux-aarch64
  - geopandas
  - h5netcdf
  - hdf5
  - ipykernel
  - ipywidgets
  - libgdal-hdf4 
  - jsonpickle
  - make
  - matplotlib
  - nbconvert
  - nbformat
  - netCDF4
  - networkx
  - numpy=2.2.6
  - opencv
  - osmnx
  - pandas
  - pip
  - polars
  - prettytable
  - pyarrow
  - pytest
  - python=3.12.11
  - python-daemon
  - pyvis
  - rasterio
  - s3fs
  - s3path
  - scikit-learn
  - seaborn
  - setuptools
  - sparse
  - tensorflow=2.18.0=cpu_py312h0267799_2
  - tiledb-py
  - tqdm
  - uvicorn
  - xarray
  - zarr=2.18.7
  
  # for docs
  - docutils
  - flit
  - furo
  - myst-nb
  - nbsphinx
  - nbsphinx-link
  - pandoc
  - sphinx
  - sphinx-autodoc-typehints
  - sphinx_rtd_theme
  - sphinxcontrib-mermaid

  #for pytest
  - pip:
      - crick
  #for web
      - titiler
      - titiler-application
      - titiler-core
      - titiler-extensions
      - titiler-mosaic
      - titiler-xarray

