# Hard requirements for running documentation generator (sphinx)
# WARNING: Keep this up-to-date!
name: OCETRA_gpu
channels:
 - conda-forge
 - nodefaults

dependencies:
  - absl-py
  - apscheduler 
  - astunparse
  - aws-c-cal
  - aws-sdk-cpp
  - awscli
  - bazel=7.4.1
  - boto3
  - bottleneck
  - cdsapi
  - cfgrib
  - cmake
  - cuda-compiler
  - cuda-cudart
  - cuda-cupti
  - cuda-libraries
  - cuda-toolkit=12.8.1
  - cuda-tools
  - cudnn=9.8.0.87
  - cloudpickle
  - cython
  - dask
  - datapi
  - dill
  - earthaccess
  - ecmwf-api-client
  - fastapi 
  - fsspec
  - gast
  - geopandas
  - google-pasta
  - grpcio
  - h5netcdf
  - h5py
  - hdf5
  - ipykernel
  - ipywidgets
  - jsonpickle
  - keras
  - libgdal-hdf4
  - lld
  - make
  - markdown
  - markdown-it-py
  - matplotlib
  - mdurl
  - namex
  - nbconvert
  - nbformat
  - nccl
  - netCDF4
  - networkx
  - numpy
  - opencv
  - openjdk
  - openmpi
  - openssl
  - opt-einsum
  - optree
  - osmnx
  - pandas
  - pillow
  - pip
  - ply
  - polars
  - prettytable
  - protobuf
  - pyarrow
  - pygments
  - pytest
  - python=3.12.11
  - python-daemon
  - pyvis
  - rasterio
  - rich
  - s3fs
  - s3path
  - scikit-learn
  - seaborn
  - setuptools
  - six
  - sparse
  - termcolor
  - thriftpy2
  - tqdm
  - typing-extensions
  - werkzeug
  - wrapt
  - xarray
  - zarr=2.18.7

  # for docs
  - docutils
  - flit
  - furo
  - myst-nb
  - nbsphinx
  - nbsphinx-link
  - pandoc
  - sphinx
  - sphinx-autodoc-typehints
  - sphinx_rtd_theme
  - pydata-sphinx-theme
  - sphinxcontrib-mermaid

  - pip:
    - crick
    - flatbuffers
    - libclang==18.1.1
    - parquet
    - thriftpy2
    - tiledb
