# Hard requirements for running documentation generator (sphinx)
# WARNING: Keep this up-to-date!
name: crest_doc
channels:
 - conda-forge

dependencies:
  - python =3.10,<3.14
  - ipykernel
  - flit >=3.9.0
  # Documentation packages
  - sphinx >=7.0.0
  - sphinx-autobuild >=2024.4.16
  - sphinx-autodoc-typehints
  - sphinx-design
  - pandoc=3.1.3
  - furo >=2023.9.10
  - pip
  - pip:
     - sphinx_autodoc_typehints
     - sphinx_rtd_theme
     - sphinx-design
     - nbsphinx
     - nbsphinx-link
     - myst-parser
     - sphinxcontrib-mermaid


