from logging.handlers import MemoryHandler
import threading


class TimedHandler(MemoryHandler):
    """ Log handler that buffers by time.

    Notes
    -----
    A time-based MemoryBuffer allows logs generated by different processes to 
    be grouped together in the log file when they are within `delay` seconds 
    of each other. However, this means the log file might contain logs that are 
    out of order temporally (by <= `delay` seconds), and writing all logs is
    delayed by <= `delay` seconds.

    One downside of this approach is that if a record is logged near the end of
    the `delay` time window, and another record is logged immediately after the
    end of that window, the two records would be close in time but would not be
    grouped in the same buffer (with the second record not being flushed for 
    another `delay` seconds). A way to address this would be to define a small 
    window of time in which any new record that is logged within that window 
    would extend the window duration. In this manner, records close in time to
    one another would be guaranteed to be within the same buffer. To avoid the
    scenario of repeatedly extending the window indefinitely, the extension 
    duration can e.g. halve after each extension. To implement this approach,
    it would likely be best to create a custom Timer class to extend the timer
    when necessary, instead of repeatedly cancelling and creating new Timers.

    Parameters
    ----------
    delay : float
        The number of seconds to wait for more records before writing the 
        current buffer contents.
    *args, **kwargs
        See MemoryHandler for details on other parameters.

    .. _MemoryHandler reference:
        https://docs.python.org/3/library/logging.handlers.html#logging.handlers.MemoryHandler

    """

    def __init__(self, delay: float, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.delay = delay
        self.timer = None


    def shouldFlush(self, *args, **kwargs):
        """ Flushes if at capacity, and otherwise starts timers when needed """

        # Ensure we aren't starting new threads during program exit
        if threading._SHUTTING_DOWN:
            return True

        # Any active timer should be canceled before flushing
        if super().shouldFlush(*args, **kwargs): 
            if self.timer is not None:
                self.timer.cancel()
            return True

        # Make the timer daemonic so we don't need to wait at program exit
        elif self.timer is None:
            self.timer = threading.Timer(self.delay, self.flush)
            self.timer.daemon = True
            self.timer.start()
        return False


    def flush(self, *args, **kwargs):
        """ Discard any existing timer object, then use MemoryHandler.flush """
        self.timer = None
        return super().flush(*args, **kwargs)


    def close(self, *args, **kwargs):
        """ Cancel any running timers before calling MemoryHandler.close """
        if self.timer is not None:
            self.timer.cancel()
        return super().close(*args, **kwargs)