from concurrent.futures import ThreadPoolExecutor, wait, FIRST_COMPLETED
from numpy.lib.stride_tricks import as_strided
from collections.abc import Callable, Collection
from dask.delayed import Delayed
from functools import partial, cached_property
from numbers import Number
from pathlib import Path 

import dask.array as da
import numpy as np 
import traceback
import logging
import time
import sys 

from crest.src.base import BaseAbstract
from crest.src.data.loading import Dataset, Sample



class Batcher(BaseAbstract):
    """Handles creating batches of data samples. 

    Parameters
    ----------
    dataset    : Dataset | list[dask.delayed.Delayed]
        Either a Crest Dataset object, or the list of delayed Sample 
        objects which is generated by calling 
        Dataset.generate_samples(compute=False). 
    batch_size : int
        Number of samples that each batch should contain. 
    workers    : int
        Number of threads to use to create batches in parallel. Note
        that twice this number of threads are actually used, as one 
        set is used for loading dataset blocks and the other set
        is used for loading samples from the chunks within a block. 
    shuffle    : bool 
        Whether samples should be shuffled to generate batches, or 
        returned in the original order of the sample array. 
    seed       : int | None
        Seed for reproducible randomness. 
    
    """
    def __init__(self, 
        dataset    : Dataset | list[Delayed],
        batch_size : int,
        features   : list = [],
        workers    : int  = 3,
        shuffle    : bool = False,
        seed       : int | None = None,
    ):
        self.samples = dataset
        self.n_batch = batch_size 
        self.workers = workers if shuffle else 1
        self.shuffle = shuffle
        self.random  = np.random.default_rng(seed)
        self.parser  = partial(self._parse, features)

        if not len(features):
            self.parser = lambda x: x 

        if not isinstance(dataset, list):
            self.samples = dataset.generate_samples(compute=False)


    def __iter__(self):
        """ Yield batches of samples """
        _Tasks.EXIT = 0

        # Samples is a list of dask.Delayed objects
        if self.shuffle: self.random.shuffle(self.samples)

        # Divide them into small subsets to operate over in parallel
        n_block = 1
        n_split = max(1, len(self.samples) // n_block) 
        subsets = np.array_split(self.samples, n_split)
        
        # Initialize a new container for leftover samples
        self._remainder = []
        
        # Create task executors for generating blocks and batches
        create_task = partial(_Tasks, workers=self.workers)
        batch_tasks = self._batch_tasks = create_task(self._batcher, capacity=50)
        block_tasks = self._block_tasks = create_task(self._combine, subsets)

        try:
            # Keep executing until all blocks and batches are processed
            while (block_tasks or batch_tasks) and not _Tasks.EXIT:
                for task in batch_tasks:
                    yield from map(self.parser, filter(len, task.result()()))
                time.sleep(0.01)

                # Clear any completed block tasks
                list(block_tasks)

            # Yield any remaining samples
            if len(self._remainder): 
                yield self.parser(self._remainder) 

        except KeyboardInterrupt: 
            print('\nReceived exit signal, cleaning up threads...') 
        except Exception as e:    
            print(f'Exception: {e}')
            print(traceback.format_exc())
        finally: 
            block_tasks.quit()
            batch_tasks.quit()


    def _combine(self, blocks, log=print, max_bytes=1e5):
        # Combine multiple blocks into a single array
        samples = da.hstack( da.compute(*blocks) )
        if samples.chunksize[0] < 10:
            samples = samples.rechunk((self.n_batch,))

        # Extract batches from each block in the array in parallel
        order = np.arange(samples.numblocks[0])
        if self.shuffle: self.random.shuffle(order)

        # Process up to 100MB at once to increase throughput,
        # and improve randomness by shuffling across blocks
        n_bytes = samples.nbytes / samples.numblocks[0]
        n_block = min(samples.numblocks[0], max(1, int(max_bytes / n_bytes)))
        extract = lambda i: order[i::n_block]
        chunks  = map(list, zip(*map(extract, range(n_block))))
        # log(f'Adding {samples.blocks.size//n_block} batch tasks')
        list(map(self._batch_tasks, map(samples.blocks.__getitem__, chunks)))

        # Ensureany remaining blocks are also processed
        remain = len(order) % n_block
        if remain: self._batch_tasks(samples.blocks[order[-remain:]])


    def _batcher(self, samples, log=print):
        # Compute the current samples and shuffle if requested
        samples = samples.compute()[:]
        if self.shuffle: self.random.shuffle(samples)

        def wrapper(samples=samples):
            """ Executed in the main thread to handle remainder samples """
            # Append any previously leftover samples
            if 0 < len(self._remainder) < self.n_batch:
                samples = np.append(self._remainder, samples, 0)

            # Calculate attributes to create a view of the samples
            n_group = len(samples) // self.n_batch
            i_size  = samples.itemsize
            shape   = (n_group, self.n_batch)
            strides = (self.n_batch*i_size, i_size)

            # Save remainder samples and yield from a strided view
            log(f'Yielding {n_group} batches: [{samples[0]}, {samples[-1]}]')
            self._remainder = samples[n_group * self.n_batch:] 
            yield from as_strided(samples, shape=shape, strides=strides) 
        return wrapper 


    def _parse(self, features: list, batch: Collection[Sample]):
        if isinstance(features[0], list):
            parse = partial(self._parse, batch=batch)
            return list(map(parse, features))
        return np.array([sample.extract(features) for sample in batch])




class _Tasks(set):
    """ Encapsulates mapping a function over a set of items, 
        while providing some additional logistical support 
        over the native Executor.map function.

        Tasks are returned as a set when waiting for them
        to complete, and so this class wraps the python set
        type in order to easily track and update the tasks
        as they complete.

    """
    EXIT = 0

    def __init__(self, 
        function : Callable, 
        items    : list   = [], 
        timeout  : Number = 0.5, 
        workers  : int    = 3,
        capacity : int | None = None,
    ):
        super().__init__()
        self.EXIT     = 0
        self.n_items  = 0
        self.timeout  = timeout 
        self.capacity = capacity
        self.function = function
        self.executor = ThreadPoolExecutor(max_workers=workers)
        self(items)


    def __repr__(self):
        return self.function.__name__


    def __call__(self, items):
        """ Apply the Task function to a new collection of items """
        if hasattr(items, 'result'):    items = items.result()
        if not isinstance(items, list): items = [items]
        self.logger.info(f'Calling {self} on {len(items)} items')
        list(map(self.submit, items))


    def __iter__(self):
        """ Retrieve completed tasks, if there are any available """
        try: 
            done, _ = wait(self, self.timeout, FIRST_COMPLETED)
            self.difference_update(done)
            yield from sorted(done, key=lambda d: d.order)
        except TimeoutError: pass


    def submit(self, item):
        """ Helper which wraps task submission """
        try: 
            # Wait for capacity in the container or EXIT to be signaled
            while (not self.EXIT) and self.full:
                time.sleep(3) 
                self.logger.debug(f'Waiting to add more {self} items')

            # If EXIT not signaled, submit the job and track its order
            if not self.EXIT: 
                submit = self.executor.submit
                future = submit(self.function, item, log=self.logger.info)
                future.order = self.n_items
                self.n_items+= 1
                self.add(future)

        except Exception as e:
            if 'new futures after shutdown' not in str(e):
                print(f'Exception in {function}: {e} ({type(e)})')
                print(traceback.format_exc())
                self.quit()


    @cached_property
    def logger(self):
        message = f'%(asctime)s | %(levelname)s | {self} | %(threadName)s | %(message)s'
        outpath = 'Batcher.log'
        handler = logging.FileHandler(outpath)
        handler.setFormatter( logging.Formatter(message) )
        Path(outpath).write_text('')

        logger  = logging.getLogger(str(self))
        logger.setLevel(logging.DEBUG)
        logger.addHandler(handler)
        return logger


    @property
    def full(self) -> bool:
        """ Checks if this container is at capacity """
        return (self.capacity is not None) and (len(self) > self.capacity)


    def quit(self):
        """ Gracefully clean up the background threads """
        self.EXIT = _Tasks.EXIT = True
        self.executor.shutdown(wait=False, cancel_futures=True)
